// ----- Platform icons + tracks data array -----

const PLATFORMS = {
  spotify: {
    label: 'Spotify',
    icon: `<svg width="13" height="13" viewBox="0 0 24 24" style="display:block">
      <circle cx="12" cy="12" r="12" fill="#1DB954"/>
      <path d="M7.5 16.3c2.8-1.6 6.4-1.4 9.1.2" stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
      <path d="M6.6 12.7c3.6-2 8-1.7 11.3.3"   stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
      <path d="M5.8 9c4.5-2.4 10-2 13.8.5"      stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
    </svg>`
  },
  soundcloud: {
    label: 'SoundCloud',
    icon: `<svg width="14" height="11" viewBox="0 0 14 11" style="display:block">
      <rect x="0"  y="5" width="2" height="6" rx="1" fill="#FF5500"/>
      <rect x="3"  y="3" width="2" height="8" rx="1" fill="#FF5500"/>
      <rect x="6"  y="0" width="2" height="11" rx="1" fill="#FF5500"/>
      <rect x="9"  y="3" width="2" height="8" rx="1" fill="#FF5500"/>
      <rect x="12" y="5" width="2" height="6" rx="1" fill="#FF5500"/>
    </svg>`
  },
  applemusic: {
    label: 'Apple Music',
    icon: `<svg width="13" height="13" viewBox="0 0 24 24" style="display:block">
      <circle cx="12" cy="12" r="12" fill="#fc3c44"/>
      <path d="M16 7.5v6.8c0 1.2-.9 2.2-2 2.2s-2-1-2-2.2.9-2.2 2-2.2c.4 0 .7.1 1 .3V9l-7 1.5v7c0 1.2-.9 2.2-2 2.2S5 18.7 5 17.5s.9-2.2 2-2.2c.4 0 .7.1 1 .3V8.5L16 7.5z" fill="white"/>
    </svg>`
  },
};

// ─── ADD YOUR TRACKS HERE ───────────────────────────────────────────────────
// work:    services you performed
// credits: additional creative roles, e.g. guitars, piano
// links:   uncomment and add URLs for streaming platforms
const tracks = [
/*
  {
    title: "Title",
    artist: "Artist",
    date: "",
    genres: [""],
    work: [""],
    credits: [],
    genreLabel: "",
    workLabel: "",
    src: "audio/",
    links: {},
  },
*/

  // ─── Jack St Jean ──────────────────────────────────────────────────────────
  {
    title: "Primadonna Girl (by Marina)",
    artist: "Jack St Jean",
    date: "202504",
    genres: ["pop", "experimental"],
    work: ["production", "recording", "composition", "guitar", "bass", "drums", "arranging"],
    credits: [],
    genreLabel: "pop / experimental",
    workLabel: "production / arranging",
    src: "audio/jsj_cover_primadonna.mp3",
    links: {},
  },
  {
    title: "The First Act [DEMO]",
    artist: "Jack St Jean",
    date: "202604",
    genres: ["indie", "folk"],
    work: ["production", "recording", "composition", "guitar", "bass", "drums"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "production",
    src: "audio/jsj_demo_the-first-act.mp3",
    links: {},
  },
  {
    title: "Say My Peace v2 [DEMO]",
    artist: "Jack St Jean",
    date: "202512",
    genres: ["funk"],
    work: ["production", "recording", "composition", "drums", "bass", "guitar"],
    credits: [],
    genreLabel: "funk",
    workLabel: "production",
    src: "audio/jsj_demo_say-my-peace.wav",
    links: {},
  },
  {
    title: "Say My Peace v1 [DEMO]",
    artist: "Jack St Jean",
    date: "202510",
    genres: ["funk", "disco"],
    work: ["production", "recording", "composition", "drums", "bass", "guitar"],
    credits: [],
    genreLabel: "funk / disco",
    workLabel: "production",
    src: "audio/jsj_demo_living-back-then.wav",
    links: {},
  },
  {
    title: "Spider Bite [DEMO]",
    artist: "Jack St Jean",
    date: "202510",
    genres: ["lofi", "indie"],
    work: ["production", "composition", "guitar", "drums"],
    credits: [],
    genreLabel: "indie / lofi",
    workLabel: "production",
    src: "audio/jsj_demo_spider-bite.wav",
    links: {},
  },
  {
    title: "Let it Die [IDEA]",
    artist: "Jack St Jean",
    date: "202509",
    genres: ["indie", "folk"],
    work: ["production", "recording", "composition", "guitar"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "production",
    src: "audio/jsj_demo_let-it-die.mp3",
    links: {},
  },
  {
    title: "Twilight [DEMO]",
    artist: "Jack St Jean",
    date: "202508",
    genres: ["lofi", "indie"],
    work: ["production", "recording", "composition", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / indie",
    workLabel: "production",
    src: "audio/jsj_demo_twilight.mp3",
    links: {},
  },
  {
    title: "No Meds [IDEA]",
    artist: "Jack St Jean",
    date: "202508",
    genres: ["lofi"],
    work: ["production", "recording", "composition", "guitar"],
    credits: [],
    genreLabel: "lofi",
    workLabel: "production",
    src: "audio/jsj_idea_no-meds.mp3",
    links: {},
  },
  {
    title: "Levi",
    artist: "Jack St Jean",
    date: "202507",
    genres: ["hiphop"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_demo_levi.mp3",
    links: {},
  },
  {
    title: "Bounce [IDEA]",
    artist: "Jack St Jean",
    date: "202504",
    genres: ["hiphop", "r&b"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / r&b",
    workLabel: "production",
    src: "audio/jsj_demo_bounce.wav",
    links: {},
  },
  {
    title: "Beta Male (w/ Jack Harlow Acapella)",
    artist: "Jack St Jean",
    date: "202506",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_beta-male.mp3",
    links: {},
  },
  {
    title: "KNX [IDEA]",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop"],
    work: ["production", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_demo_knx.mp3",
    links: {},
  },
  {
    title: "Butter Barn (detroit remix)",
    artist: "Jack St Jean",
    date: "202505",
    genres: ["hiphop", "detroit"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / detroit",
    workLabel: "production",
    src: "audio/jsj_butter-barn.mp3",
    links: {},
  },
  {
    title: "Louvre [IDEA]",
    artist: "Jack St Jean",
    date: "202505",
    genres: ["hiphop", "boom bap"],
    work: ["production", "drums"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production (drums)",
    src: "audio/jsj_demo_louvre.mp3",
    links: {},
  },
  {
    title: "Jack's Riff",
    artist: "Jack St Jean",
    date: "202404",
    genres: ["lofi", "slowcore"],
    work: ["production", "drums", "guitar"],
    credits: [],
    genreLabel: "lofi / slowcore",
    workLabel: "production",
    src: "audio/jsj_jacks-riff.wav",
    links: {},
  },
  {
    title: "Liam's Riff",
    artist: "Jack St Jean",
    date: "202404",
    genres: ["lofi", "slowcore"],
    work: ["production", "drums"],
    credits: [],
    genreLabel: "lofi / slowcore",
    workLabel: "production",
    src: "audio/jsj_liams-riff.wav",
    links: {},
  },
  {
    title: "Dee Jay [IDEA]",
    artist: "Jack St Jean",
    date: "202503",
    genres: ["hiphop"],
    work: ["production", "composition", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_demo_deejay.wav",
    links: {},
  },
  {
    title: "Champion",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop", "trap"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_demo_champion.mp3",
    links: {},
  },
  {
    title: "Upop Bfunk",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["brazilian funk"],
    work: ["production"],
    credits: [],
    genreLabel: "brazilian funk",
    workLabel: "production",
    src: "audio/jsj_upop.wav",
    links: {},
  },
  {
    title: "Pork Pie [DEMO]",
    artist: "Jack St Jean",
    date: "202309",
    genres: ["hiphop", "boom bap"],
    work: ["production", "composition", "guitar", "bass", "drums"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_demo_pork-pie.wav",
    links: {},
  },
  {
    title: "Listen to Me",
    artist: "Jack St Jean",
    date: "202405",
    genres: ["hiphop", "r&b", "chill"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "chill / hiphop / r&b",
    workLabel: "production",
    src: "audio/jsj_demo_listen-to-me.wav",
    links: {},
  },
  {
    title: "Accordian",
    artist: "Jack St Jean",
    date: "202411",
    genres: ["brazilian funk"],
    work: ["production"],
    credits: [],
    genreLabel: "brazilian funk",
    workLabel: "production",
    src: "audio/jsj_accordian-funk.wav",
    links: {},
  },
  {
    title: "Candyland [IDEA]",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop", "trap"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_demo_candyland.mp3",
    links: {},
  },
  {
    title: "Autumn Leaves (by Joseph Kosma) [DEMO]",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["r&b"],
    work: ["production", "arranging", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production / arranging",
    src: "audio/jsj_demo_autumn-leaves.wav",
    links: {},
  },
  {
    title: "But Not For Me (by Gershwin) [DEMO]",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["r&b"],
    work: ["production", "arranging", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production / arranging",
    src: "audio/jsj_demo_but-not-for-me.wav",
    links: {},
  },
  {
    title: "Yuck",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["hiphop", "swag"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_demo_yuck.wav",
    links: {},
  },
  {
    title: "You Me",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop"],
    work: ["production", "drums", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_you-me.wav",
    links: {},
  },
  {
    title: "Some Times I Just [IDEA]",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop", "dance"],
    work: ["production", "composition", "guitar", "drums", "bass"],
    credits: [],
    genreLabel: "hiphop / dance",
    workLabel: "production",
    src: "audio/jsj_demo_some-times-i-just.mp3",
    links: {},
  },
  {
    title: "Terry Terrifying [IDEA]",
    artist: "Jack St Jean",
    date: "202406",
    genres: ["hiphop", "boom bap"],
    work: ["production", "composition", "guitar", "drums"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_demo_terry-terrifying.mp3",
    links: {},
  },
  {
    title: "Secunda, New Jersey",
    artist: "Jack St Jean",
    date: "202405",
    genres: ["jersey club"],
    work: ["production"],
    credits: [],
    genreLabel: "jersey club",
    workLabel: "production",
    src: "audio/jsj_secunda-nj.wav",
    links: {},
  },
  {
    title: "Front Me",
    artist: "Jack St Jean",
    date: "202401",
    genres: ["hiphop", "boom bap"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_demo_front-me.mp3",
    links: {},
  },
  {
    title: "November",
    artist: "Jack St Jean",
    date: "202311",
    genres: ["idk"],
    work: ["production", "recording", "composition", "drums", "guitar"],
    credits: [],
    genreLabel: "idk",
    workLabel: "production / recording",
    src: "audio/jsj_demo_november.wav",
    links: {},
  },
  {
    title: "Bummer [DEMO]",
    artist: "Jack St Jean",
    date: "202311",
    genres: ["hiphop", "dilla time"],
    work: ["production", "recording", "guitar", "drums", "bass", "composition"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production / recording",
    src: "audio/jsj_demo_bummer.wav",
    links: {},
  },
  {
    title: "Airplane Food",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_airplane-food_1.mp3",
    links: {},
  },
  {
    title: "Andybeat",
    artist: "Jack St Jean",
    date: "202110",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_andy_1.mp3",
    links: {},
  },
  {
    title: "Bedside",
    artist: "Jack St Jean",
    date: "202211",
    genres: ["r&b", "neosoul"],
    work: ["production"],
    credits: [],
    genreLabel: "r&b / neosoul",
    workLabel: "production",
    src: "audio/jsj_bedside_1.mp3",
    links: {},
  },
  {
    title: "Burnout",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_burnout (no Bronson)_1.mp3",
    links: {},
  },
  {
    title: "Burnout (w/ Action Bronson Acapella)",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_burnout_1.mp3",
    links: {},
  },
  {
    title: "Cami",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_cami_1.mp3",
    links: {},
  },
  {
    title: "Cheetah",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["r&b"],
    work: ["production", "bass", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production",
    src: "audio/jsj_cheetah_1.mp3",
    links: {},
  },
  {
    title: "Collage",
    artist: "Jack St Jean",
    date: "202211",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_collage_1.mp3",
    links: {},
  },
  {
    title: "Discovery",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["dnb"],
    work: ["production"],
    credits: [],
    genreLabel: "dnb",
    workLabel: "production",
    src: "audio/jsj_discovery_1.mp3",
    links: {},
  },
  {
    title: "Dummy",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["dnb"],
    work: ["production"],
    credits: [],
    genreLabel: "dnb",
    workLabel: "production",
    src: "audio/jsj_dummy-dnb_1.mp3",
    links: {},
  },
  {
    title: "Elf Root",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["hiphop"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_elf-root_1.mp3",
    links: {},
  },
  {
    title: "Flat Footed",
    artist: "Jack St Jean",
    date: "202203",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_flat-footed202301_1.mp3",
    links: {},
  },
  {
    title: "Follow Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_follow-me_1.mp3",
    links: {},
  },
  {
    title: "Fugue",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_fugue_1.mp3",
    links: {},
  },
  {
    title: "Golden Hour",
    artist: "Jack St Jean",
    date: "202205",
    genres: ["hiphop", "boom bap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_golden-hour_1.mp3",
    links: {},
  },
  {
    title: "Gucci Bergers (Bass Boosted)",
    artist: "Jack St Jean",
    date: "202410",
    genres: ["hiphop", "stupid"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / stupid",
    workLabel: "production",
    src: "audio/jsj_gucci-bergers_1.mp3",
    links: {},
  },
  {
    title: "Hungry",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop", "experimental"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / experimental",
    workLabel: "production",
    src: "audio/jsj_hungry_1.mp3",
    links: {},
  },
  {
    title: "I Already Won",
    artist: "Jack St Jean",
    date: "202301",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_i-already-won_1.mp3",
    links: {},
  },
  {
    title: "Gooby",
    artist: "Jack St Jean",
    date: "202112",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_idea_gooby202112_1.mp3",
    links: {},
  },
  {
    title: "I'm 6'4",
    artist: "Jack St Jean",
    date: "202305",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_im-6-4_1.mp3",
    links: {},
  },
  {
    title: "Be Right There (w/ Mos Def Acapella)",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_i’ll-be-there_1.mp3",
    links: {},
  },
  {
    title: "Be Right There",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_i’ll-be-there_1.mp3",
    links: {},
  },
  {
    title: "Leave It All to Me (from iCarly)",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["experimental"],
    work: ["production", "arranging"],
    credits: [],
    genreLabel: "experimental",
    workLabel: "production",
    src: "audio/jsj_leave-it-all-to-me_1.mp3",
    links: {},
  },
  {
    title: "Moonroof",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_moonroof_1.mp3",
    links: {},
  },
  {
    title: "Murder",
    artist: "Jack St Jean",
    date: "202303",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_murder-v2_1.mp3",
    links: {},
  },
  {
    title: "My World",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop", "boom bap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_my-world_1.mp3",
    links: {},
  },
  {
    title: "Nerevar",
    artist: "Jack St Jean",
    date: "202302",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_nerevar_1.mp3",
    links: {},
  },
  {
    title: "Nineteen",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["indie", "pop", "dance"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "indie / pop / dance",
    workLabel: "production",
    src: "audio/jsj_nineteen_1.mp3",
    links: {},
  },
  {
    title: "Nocturne",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["dance", "stupid"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / stupid",
    workLabel: "production",
    src: "audio/jsj_nocturne_1.mp3",
    links: {},
  },
  {
    title: "Please Clap",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["dance", "dariacore"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / dariacore",
    workLabel: "production",
    src: "audio/jsj_please-clap_1.mp3",
    links: {},
  },
  {
    title: "Pray for Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["experimental"],
    work: ["production"],
    credits: [],
    genreLabel: "experimental",
    workLabel: "production",
    src: "audio/jsj_pray-for-me_1.mp3",
    links: {},
  },
  {
    title: "Segovia",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_segovia_1.mp3",
    links: {},
  },
  {
    title: "Skipping Rocks",
    artist: "Jack St Jean",
    date: "202309",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_skipping-rocks_1.mp3",
    links: {},
  },
  {
    title: "Stick It",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_stick-it_1.mp3",
    links: {},
  },
  {
    title: "Summertime (by Gershwin)",
    artist: "Jack St Jean",
    date: "202304",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_summertime_1.mp3",
    links: {},
  },
  {
    title: "Take Off",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_take-off_1.mp3",
    links: {},
  },
  {
    title: "The Ox",
    artist: "Jack St Jean",
    date: "202111",
    genres: ["hiphop", "rock"],
    work: ["production", "guitar"],
    credits: [],
    genreLabel: "hiphop / rock",
    workLabel: "production",
    src: "audio/jsj_the-ox_1.mp3",
    links: {},
  },
  {
    title: "This Beat Ended Hip Hop for Good",
    artist: "Jack St Jean",
    date: "202103",
    genres: ["hiphop", "stupid"],
    work: ["composition", "guitar"],
    credits: [],
    genreLabel: "hiphop / stupid",
    workLabel: "composition",
    src: "audio/jsj_this-beat-ended-hip-hop-for-good_1.mp3",
    links: {},
  },
  {
    title: "Trying League of Legends",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["dance", "dariacore"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / dariacore",
    workLabel: "production",
    src: "audio/jsj_trying-league-of-legends_1.mp3",
    links: {},
  },
  {
    title: "You and Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_u&e_1.mp3",
    links: {},
  },
  {
    title: "U&I v1",
    artist: "Jack St Jean",
    date: "202304",
    genres: ["hiphop", "lofi"],
    work: ["production", "composition", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / hiphop",
    workLabel: "production",
    src: "audio/jsj_u&i-v1_1.mp3",
    links: {},
  },
  {
    title: "U&I v2",
    artist: "Jack St Jean",
    date: "202305",
    genres: ["experimental", "lofi"],
    work: ["production", "composition", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / experimental",
    workLabel: "production",
    src: "audio/jsj_u&i-v2_1.mp3",
    links: {},
  },
  {
    title: "Up Early",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_up-early_1.mp3",
    links: {},
  },
  {
    title: "Westcoast",
    artist: "Jack St Jean",
    date: "202203",
    genres: ["hiphop", "g-funk"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / g-funk",
    workLabel: "production",
    src: "audio/jsj_westcoast_1.mp3",
    links: {},
  },

  // ─── Cielago's Bootlegs ────────────────────────────────────────────────────
  {
    title: "All My Friends Are Stoners",
    artist: "Cielago's Bootlegs",
    date: "202406",
    genres: ["indie", "rock"],
    work: ["mixing"],
    credits: ["production"],
    genreLabel: "indie / rock",
    workLabel: "mixing / production (end)",
    src: "audio/cielagos-bootlegs_all-my-friends-are-stoners.wav",
    links: {},
  },

  // ─── Wizedev ───────────────────────────────────────────────────────────────
  {
    title: "Intro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["guitar", "composition"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_intro.mp3",
    links: {},
  },
  {
    title: "Rewind",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["composition"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_rewind.mp3",
    links: {},
  },
  {
    title: "I'll Be There",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["composition", "bass"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_i'll-be-there.mp3",
    links: {},
  },
  {
    title: "Long Night",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["composition"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_long-night.mp3",
    links: {},
  },
  {
    title: "Take My Hand",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["composition"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_take-my-hand.mp3",
    links: {},
  },
  {
    title: "Zion",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["composition"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_zion.mp3",
    links: {},
  },
  {
    title: "Outro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_outro.mp3",
    links: {},
  },

  // ─── Porcelain Parrot ──────────────────────────────────────────────────────
  {
    title: "Dreams",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_dreams.wav",
    links: {},
  },
  {
    title: "Volume Negates Luck",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_volume-negates-luck.wav",
    links: {},
  },

  // ─── Lemongrass Roots Band ─────────────────────────────────────────────────
  {
    title: "Whiskey Before Breakfast",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_whiskey-before-breakfast.wav",
    links: {},
  },
  {
    title: "Tswv Yexus Lub Npe",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_tswv-yexus-lub-npe.wav",
    links: {},
  },
  {
    title: "Old Home Place",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_old-home-place.wav",
    links: {},
  },
  {
    title: "Kuv Tus Kwvluag",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_kuv-tus-kwvluag.wav",
    links: {},
  },
  {
    title: "East Tennessee Blues",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_east-tennessee-blues.wav",
    links: {},
  },

  // ─── kinfolk ───────────────────────────────────────────────────────────────
  {
    title: "She's Not Like Me",
    artist: "kinfolk",
    date: "202504",
    genres: ["indie", "folk"],
    work: ["production", "recording", "mixing", "mastering"],
    credits: ["composition", "arranging", "guitar", "bass"],
    genreLabel: "indie / folk",
    workLabel: "production · composition · arranging · recording · mixing · mastering",
    src: "audio/kinfolk_shes-not-like-me.wav",
    links: {},
  },

  // ─── Kai Moscow ────────────────────────────────────────────────────────────
  {
    title: "Pinball Number Count (from Sesame Street)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_pinball-number-count.wav",
    links: {},
  },
  {
    title: "Le Bleury (covering Anomalie)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_le-bleury.wav",
    links: {},
  },

  // ─── Industrial Coffee Pot ─────────────────────────────────────────────────
  {
    title: "Just Shwangen - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_just-shwangen.wav",
    links: {},
  },
  {
    title: "To the Moon River - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_to-the-moon-river.wav",
    links: {},
  },
  {
    title: "San Francisco Pilot - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_san-francisco-pilot.wav",
    links: {},
  },
  {
    title: "Softly - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_softly.wav",
    links: {},
  },
  {
    title: "Rain and Snow - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / bossa",
    workLabel: "mixing · mastering",
    src: "audio/icp_rain-and-snow.wav",
    links: {},
  },
  {
    title: "Our Love - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_our-love.wav",
    links: {},
  },
  {
    title: "Another Case of the No Good Reason - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_another-case.wav",
    links: {},
  },
  {
    title: "Just Friends - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_just-friends.wav",
    links: {},
  },

  // ─── Floral Dilemma ────────────────────────────────────────────────────────
  {
    title: "Edging on Merrimon",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/floral-dilemma_edging-on-merrimon.wav",
    links: {},
  },
  {
    title: "Misty Rain",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "production · recording · mixing · mastering",
    src: "audio/floral-dilemma_misty-rain.wav",
    links: {},
  },

  // ─── Donnie Black ──────────────────────────────────────────────────────────
  {
    title: "Summer's Over (Introlude)",
    artist: "Donnie Black",
    date: "202509",
    genres: ["r&b"],
    work: ["production", "recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · recording · mixing · mastering",
    src: "audio/donnie-black_summers-over.wav",
    links: {},
  },
  {
    title: "Be Free",
    artist: "Donnie Black",
    date: "",
    genres: [],
    work: [],
    credits: [],
    genreLabel: "",
    workLabel: "",
    src: "audio/donnie-black_be-free.wav",
    links: {},
  },

  // ─── Frances Eliza ─────────────────────────────────────────────────────────
  {
    title: "Words I Didn't Say",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "pop", "rock"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / pop / rock",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_words-i-didn't-say.wav",
    links: {},
  },
  {
    title: "Drove Me Away",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "folk"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_drove-me-away.wav",
    links: {},
  },
  {
    title: "Notice Me",
    artist: "Frances Eliza",
    date: "202305",
    genres: ["indie", "rock"],
    work: ["production", "recording", "mixing"],
    credits: ["guitar"],
    genreLabel: "indie / rock",
    workLabel: "production · recording · mixing",
    src: "audio/frances-eliza_notice-me.wav",
    links: {},
  },
];
// ───────────────────────────────────────────────────────────────────────────
