// ----- Platform icons + tracks data array -----

const PLATFORMS = {
  spotify: {
    label: 'Spotify',
    icon: `<svg width="13" height="13" viewBox="0 0 24 24" style="display:block">
      <circle cx="12" cy="12" r="12" fill="#1DB954"/>
      <path d="M7.5 16.3c2.8-1.6 6.4-1.4 9.1.2" stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
      <path d="M6.6 12.7c3.6-2 8-1.7 11.3.3"   stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
      <path d="M5.8 9c4.5-2.4 10-2 13.8.5"      stroke="white" stroke-width="1.6" stroke-linecap="round" fill="none"/>
    </svg>`
  },
  soundcloud: {
    label: 'SoundCloud',
    icon: `<svg width="14" height="11" viewBox="0 0 14 11" style="display:block">
      <rect x="0"  y="5" width="2" height="6" rx="1" fill="#FF5500"/>
      <rect x="3"  y="3" width="2" height="8" rx="1" fill="#FF5500"/>
      <rect x="6"  y="0" width="2" height="11" rx="1" fill="#FF5500"/>
      <rect x="9"  y="3" width="2" height="8" rx="1" fill="#FF5500"/>
      <rect x="12" y="5" width="2" height="6" rx="1" fill="#FF5500"/>
    </svg>`
  },
  applemusic: {
    label: 'Apple Music',
    icon: `<svg width="13" height="13" viewBox="0 0 24 24" style="display:block">
      <circle cx="12" cy="12" r="12" fill="#fc3c44"/>
      <path d="M16 7.5v6.8c0 1.2-.9 2.2-2 2.2s-2-1-2-2.2.9-2.2 2-2.2c.4 0 .7.1 1 .3V9l-7 1.5v7c0 1.2-.9 2.2-2 2.2S5 18.7 5 17.5s.9-2.2 2-2.2c.4 0 .7.1 1 .3V8.5L16 7.5z" fill="white"/>
    </svg>`
  },
};

// ─── ADD YOUR TRACKS HERE ───────────────────────────────────────────────────
// work:    services you performed (used for "My Work" filter)
// credits: additional creative roles, e.g. guitars, piano (used for "Credits" filter)
// links:   uncomment and add URLs for streaming platforms
const tracks = [
  {
    title: "Intro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["guitar"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_intro.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Rewind",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_rewind.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "I'll Be There",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: ["bass"],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_i'll-be-there.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Long Night",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_long-night.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Take My Hand",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_take-my-hand.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Zion",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_zion.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Outro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_outro.mp3",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Dreams",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_dreams.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Volume Negates Luck",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_volume-negates-luck.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Whiskey Before Breakfast",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_whiskey-before-breakfast.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Tswv Yexus Lub Npe",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_tswv-yexus-lub-npe.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Old Home Place",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_old-home-place.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Kuv Tus Kwvluag",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_kuv-tus-kwvluag.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "East Tennessee Blues",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_east-tennessee-blues.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "She's Not Like Me",
    artist: "kinfolk",
    date: "202504",
    genres: ["indie", "folk"],
    work: ["production", "recording", "mixing", "mastering"],
    credits: ["composition", "arranging", "guitar", "bass"],
    genreLabel: "indie / folk",
    workLabel: "production · composition · arranging · recording · mixing · mastering",
    src: "audio/kinfolk_shes-not-like-me.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Pinball Number Count (from Sesame Street)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_pinball-number-count.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Le Bleury (covering Anomalie)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_le-bleury.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Just Shwangen - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_another-case.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "To the Moon River - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_to-the-moon-river.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "San Francisco Pilot - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_to-the-moon-river.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Softly - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_softly.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Rain and Snow - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / bossa",
    workLabel: "mixing · mastering",
    src: "audio/icp_rain-and-snow.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Our Love - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_our-love.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Another Case of the No Good Reason - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_another-case.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Just Friends - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_softly.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Edging on Merrimon",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/floral-dilemma_edging-on-merrimon.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Misty Rain",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "production · recording · mixing · mastering",
    src: "audio/floral-dilemma_misty-rain.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Summer's Over (Introlude)",
    artist: "Donnie Black",
    date: "202509",
    genres: ["r&b"],
    work: ["production", "recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · recording · mixing · mastering",
    src: "audio/donnie-black_summers-over.wav",
    links: {
      // spotify:    "https://open.spotify.com/track/...",
      // soundcloud: "https://soundcloud.com/...",
    },
  },
  {
    title: "Words I Didn't Say",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "pop", "rock"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / pop / rock",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_words-i-didn't-say.wav",
    links: {
      // spotify: "https://open.spotify.com/track/...",
    },
  },
  {
    title: "Drove Me Away",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "folk"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_drove-me-away.wav",
    links: {},
  },
  {
    title: "Notice Me",
    artist: "Frances Eliza",
    date: "202305",
    genres: ["indie", "rock"],
    work: ["production", "recording", "mixing"],
    credits: ["guitar"],
    genreLabel: "indie / rock",
    workLabel: "production · recording · mixing",
    src: "audio/frances-eliza_notice-me.wav",
    links: {},
  },
];
// ───────────────────────────────────────────────────────────────────────────
