// ----- Platform icons + tracks data array -----

const PLATFORMS = {
  spotify: {
    label: 'Spotify',
    icon: `<img src="https://cdn.simpleicons.org/spotify/1DB954" alt="Spotify">`
  },
  applemusic: {
    label: 'Apple Music',
    icon: `<img src="https://cdn.simpleicons.org/applemusic/FC3C44" alt="Apple Music">`
  },
  youtube: {
    label: 'YouTube',
    icon: `<img src="https://cdn.simpleicons.org/youtube/FF0000" alt="YouTube">`
  },
  soundcloud: {
    label: 'SoundCloud',
    icon: `<img src="https://cdn.simpleicons.org/soundcloud/FF5500" alt="SoundCloud">`
  },
  bandcamp: {
    label: 'Bandcamp',
    icon: `<img src="https://cdn.simpleicons.org/bandcamp/1DA0C3" alt="Bandcamp">`
  },
};

// ─── ADD YOUR TRACKS HERE ───────────────────────────────────────────────────
// work:    services you performed
// credits: additional creative roles, e.g. guitars, piano
// links:   uncomment and add URLs for streaming platforms
const tracks = [
/*
  {
    title: "Title",
    artist: "Artist",
    date: "",
    genres: [""],
    work: [""],
    credits: [],
    genreLabel: "",
    workLabel: "",
    src: "audio/",
    links: {},
  },
*/

  // ─── Jack St Jean ──────────────────────────────────────────────────────────
  {
    title: "Primadonna Girl (by Marina) [UNFINISHED]",
    artist: "Jack St Jean",
    date: "202504",
    genres: ["pop", "experimental"],
    work: ["production", "recording", "composition", "guitar", "bass", "drums", "arranging"],
    credits: [],
    genreLabel: "pop / experimental",
    workLabel: "production · recording · composition · guitar · bass · drums · arranging",
    src: "audio/jsj_cover_primadonna.mp3",
    links: {},
  },
  {
    title: "The First Act [DEMO]",
    artist: "Jack St Jean",
    date: "202604",
    genres: ["indie", "folk"],
    work: ["production", "recording", "composition", "guitar", "bass", "drums"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "production · recording · composition · guitar · bass · drums",
    src: "audio/jsj_demo_the-first-act.mp3",
    links: {},
  },
  {
    title: "Say My Peace v2 [DEMO]",
    artist: "Jack St Jean",
    date: "202512",
    genres: ["funk"],
    work: ["production", "recording", "composition", "drums", "bass", "guitar"],
    credits: [],
    genreLabel: "funk",
    workLabel: "production · recording · composition · drums · bass · guitar",
    src: "audio/jsj_demo_say-my-peace.wav",
    links: {},
  },
  {
    title: "Say My Peace v1 [DEMO]",
    artist: "Jack St Jean",
    date: "202510",
    genres: ["funk", "disco"],
    work: ["production", "recording", "composition", "drums", "bass", "guitar"],
    credits: [],
    genreLabel: "funk / disco",
    workLabel: "production · recording · composition · drums · bass · guitar",
    src: "audio/jsj_demo_living-back-then.wav",
    links: {},
  },
  {
    title: "Spider Bite [DEMO]",
    artist: "Jack St Jean",
    date: "202510",
    genres: ["lofi", "indie"],
    work: ["production", "composition", "guitar", "drums"],
    credits: [],
    genreLabel: "indie / lofi",
    workLabel: "production · composition · guitar · drums",
    src: "audio/jsj_demo_spider-bite.wav",
    links: {},
  },
  {
    title: "Let it Die [IDEA]",
    artist: "Jack St Jean",
    date: "202509",
    genres: ["indie", "folk"],
    work: ["production", "recording", "composition", "guitar"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "production · recording · composition · guitar",
    src: "audio/jsj_demo_let-it-die.mp3",
    links: {},
  },
  {
    title: "Twilight [DEMO]",
    artist: "Jack St Jean",
    date: "202508",
    genres: ["lofi", "indie"],
    work: ["production", "recording", "composition", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / indie",
    workLabel: "production · recording · composition · drums · guitar · bass",
    src: "audio/jsj_demo_twilight.mp3",
    links: {},
  },
  {
    title: "No Meds [IDEA]",
    artist: "Jack St Jean",
    date: "202508",
    genres: ["lofi"],
    work: ["production", "recording", "composition", "guitar"],
    credits: [],
    genreLabel: "lofi",
    workLabel: "production · recording · composition · guitar",
    src: "audio/jsj_idea_no-meds.mp3",
    links: {},
  },
  {
    title: "Levi",
    artist: "Jack St Jean",
    date: "202507",
    genres: ["hiphop"],
    work: ["production", "composition", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition · guitar · bass",
    src: "audio/jsj_demo_levi.mp3",
    links: {},
  },
  {
    title: "Bounce [IDEA]",
    artist: "Jack St Jean",
    date: "202504",
    genres: ["hiphop", "r&b"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / r&b",
    workLabel: "production · composition",
    src: "audio/jsj_demo_bounce.wav",
    links: {},
  },
  {
    title: "Beta Male (w/ Jack Harlow Acapella)",
    artist: "Jack St Jean",
    date: "202506",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_beta-male.mp3",
    links: {},
  },
  {
    title: "KNX [IDEA]",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop", "dilla time"],
    work: ["production", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production · drums · guitar · bass",
    src: "audio/jsj_demo_knx.mp3",
    links: {},
  },
  {
    title: "Butter Barn (detroit remix)",
    artist: "Jack St Jean",
    date: "202505",
    genres: ["hiphop", "detroit", "stupid"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / detroit / stupid",
    workLabel: "production",
    src: "audio/jsj_butter-barn.mp3",
    links: {},
  },
  {
    title: "Louvre [IDEA]",
    artist: "Jack St Jean",
    date: "202505",
    genres: ["hiphop", "boom bap"],
    work: ["production", "drums"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production · drums",
    src: "audio/jsj_demo_louvre.mp3",
    links: {},
  },
  {
    title: "Jack's Riff",
    artist: "Jack St Jean",
    date: "202404",
    genres: ["lofi", "slowcore"],
    work: ["production", "drums", "guitar"],
    credits: [],
    genreLabel: "lofi / slowcore",
    workLabel: "production · drums · guitar",
    src: "audio/jsj_jacks-riff.wav",
    links: {},
  },
  {
    title: "Liam's Riff",
    artist: "Jack St Jean",
    date: "202404",
    genres: ["lofi", "slowcore"],
    work: ["production", "drums"],
    credits: [],
    genreLabel: "lofi / slowcore",
    workLabel: "production · drums",
    src: "audio/jsj_liams-riff.wav",
    links: {},
  },
  {
    title: "Dee Jay [IDEA]",
    artist: "Jack St Jean",
    date: "202503",
    genres: ["hiphop"],
    work: ["production", "composition", "drums", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition · drums · guitar · bass",
    src: "audio/jsj_demo_deejay.wav",
    links: {},
  },
  {
    title: "Champion",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop", "trap"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production · composition",
    src: "audio/jsj_demo_champion.mp3",
    links: {},
  },
  {
    title: "Upop Bfunk",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["brazilian funk"],
    work: ["production"],
    credits: [],
    genreLabel: "brazilian funk",
    workLabel: "production",
    src: "audio/jsj_upop.wav",
    links: {},
  },
  {
    title: "Pork Pie [DEMO]",
    artist: "Jack St Jean",
    date: "202309",
    genres: ["hiphop", "boom bap"],
    work: ["production", "composition", "guitar", "bass", "drums"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production · composition · guitar · bass · drums",
    src: "audio/jsj_demo_pork-pie.wav",
    links: {},
  },
  {
    title: "Listen to Me",
    artist: "Jack St Jean",
    date: "202405",
    genres: ["hiphop", "r&b", "chill"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "chill / hiphop / r&b",
    workLabel: "production · composition · guitar",
    src: "audio/jsj_demo_listen-to-me.wav",
    links: {},
  },
  {
    title: "Accordian",
    artist: "Jack St Jean",
    date: "202411",
    genres: ["brazilian funk"],
    work: ["production"],
    credits: [],
    genreLabel: "brazilian funk",
    workLabel: "production",
    src: "audio/jsj_accordian-funk.wav",
    links: {},
  },
  {
    title: "Candyland [IDEA]",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop", "trap"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production · composition",
    src: "audio/jsj_demo_candyland.mp3",
    links: {},
  },
  {
    title: "Autumn Leaves (by Joseph Kosma) [DEMO]",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["r&b"],
    work: ["production", "arranging", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · arranging · guitar",
    src: "audio/jsj_demo_autumn-leaves.wav",
    links: {},
  },
  {
    title: "But Not For Me (by Gershwin) [DEMO]",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["r&b"],
    work: ["production", "arranging", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · arranging · guitar",
    src: "audio/jsj_demo_but-not-for-me.wav",
    links: {},
  },
  {
    title: "Yuck",
    artist: "Jack St Jean",
    date: "202409",
    genres: ["hiphop", "swag"],
    work: ["production", "composition"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production · composition",
    src: "audio/jsj_demo_yuck.wav",
    links: {},
  },
  {
    title: "Umie",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop"],
    work: ["production", "drums", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · drums · bass",
    src: "audio/jsj_you-me.wav",
    links: {},
  },
  {
    title: "Some Times I Just [IDEA]",
    artist: "Jack St Jean",
    date: "202408",
    genres: ["hiphop", "dance"],
    work: ["production", "composition", "guitar", "drums", "bass"],
    credits: [],
    genreLabel: "hiphop / dance",
    workLabel: "production · composition · guitar · drums · bass",
    src: "audio/jsj_demo_some-times-i-just.mp3",
    links: {},
  },
  {
    title: "Terry Terrifying [IDEA]",
    artist: "Jack St Jean",
    date: "202406",
    genres: ["hiphop", "dilla time"],
    work: ["production", "composition", "guitar", "drums"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production · composition · guitar · drums",
    src: "audio/jsj_demo_terry-terrifying.mp3",
    links: {},
  },
  {
    title: "Secunda, New Jersey",
    artist: "Jack St Jean",
    date: "202405",
    genres: ["jersey club"],
    work: ["production"],
    credits: [],
    genreLabel: "jersey club",
    workLabel: "production",
    src: "audio/jsj_secunda-nj.wav",
    links: {},
  },
  {
    title: "Front Me",
    artist: "Jack St Jean",
    date: "202401",
    genres: ["hiphop", "boom bap"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production · composition · guitar",
    src: "audio/jsj_demo_front-me.mp3",
    links: {},
  },
  {
    title: "November",
    artist: "Jack St Jean",
    date: "202311",
    genres: ["idk"],
    work: ["production", "recording", "composition", "drums", "guitar"],
    credits: [],
    genreLabel: "idk",
    workLabel: "production · recording · composition · drums · guitar",
    src: "audio/jsj_demo_november.wav",
    links: {},
  },
  {
    title: "Bummer [DEMO]",
    artist: "Jack St Jean",
    date: "202311",
    genres: ["hiphop", "dilla time"],
    work: ["production", "recording", "guitar", "drums", "bass", "composition"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production · recording · guitar · drums · bass · composition",
    src: "audio/jsj_demo_bummer.wav",
    links: {},
  },
  {
    title: "Airplane Food",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_airplane-food_1.mp3",
    links: {},
  },
  {
    title: "Andybeat",
    artist: "Jack St Jean",
    date: "202110",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_andy_1.mp3",
    links: {},
  },
  {
    title: "Bedside",
    artist: "Jack St Jean",
    date: "202211",
    genres: ["r&b", "neosoul"],
    work: ["production"],
    credits: [],
    genreLabel: "r&b / neosoul",
    workLabel: "production",
    src: "audio/jsj_bedside_1.mp3",
    links: {},
  },
  {
    title: "Burnout",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_burnout (no Bronson)_1.mp3",
    links: {},
  },
  {
    title: "Burnout (w/ Action Bronson Acapella)",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_burnout_1.mp3",
    links: {},
  },
  {
    title: "Cami [JAM]",
    artist: "Jack St Jean",
    date: "202501",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_cami_1.mp3",
    links: {},
  },
  {
    title: "Cheetah",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["r&b"],
    work: ["production", "bass", "guitar"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · bass · guitar",
    src: "audio/jsj_cheetah_1.mp3",
    links: {},
  },
  {
    title: "Collage",
    artist: "Jack St Jean",
    date: "202211",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_collage_1.mp3",
    links: {},
  },
  {
    title: "Discovery",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["dnb"],
    work: ["production"],
    credits: [],
    genreLabel: "dnb",
    workLabel: "production",
    src: "audio/jsj_discovery_1.mp3",
    links: {},
  },
  {
    title: "Dummy (w/ Kendrick Lamar Acapella)",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["dnb"],
    work: ["production"],
    credits: [],
    genreLabel: "dnb",
    workLabel: "production",
    src: "audio/jsj_dummy-dnb_1.mp3",
    links: {},
  },
  {
    title: "Elf Root",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["hiphop"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition · guitar",
    src: "audio/jsj_elf-root_1.mp3",
    links: {},
  },
  {
    title: "Flat Footed",
    artist: "Jack St Jean",
    date: "202203",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_flat-footed202301_1.mp3",
    links: {},
  },
  {
    title: "Follow Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_follow-me_1.mp3",
    links: {},
  },
  {
    title: "Fugue",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_fugue_1.mp3",
    links: {},
  },
  {
    title: "Golden Hour",
    artist: "Jack St Jean",
    date: "202205",
    genres: ["hiphop", "boom bap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_golden-hour_1.mp3",
    links: {},
  },
  {
    title: "Gucci Bergers (Bass Boosted) (Volume Warning)",
    artist: "Jack St Jean",
    date: "202410",
    genres: ["hiphop", "stupid"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / stupid",
    workLabel: "production",
    src: "audio/jsj_gucci-bergers_1.mp3",
    links: {},
  },
  {
    title: "Hungry",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop", "experimental"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / experimental",
    workLabel: "production",
    src: "audio/jsj_hungry_1.mp3",
    links: {},
  },
  {
    title: "I Already Won",
    artist: "Jack St Jean",
    date: "202301",
    genres: ["hiphop", "swag"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / swag",
    workLabel: "production",
    src: "audio/jsj_i-already-won_1.mp3",
    links: {},
  },
  {
    title: "Gooby",
    artist: "Jack St Jean",
    date: "202112",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_idea_gooby202112_1.mp3",
    links: {},
  },
  {
    title: "I'm 6'4",
    artist: "Jack St Jean",
    date: "202305",
    genres: ["hiphop"],
    work: ["production", "guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_im-6-4_1.mp3",
    links: {},
  },
  {
    title: "Be Right There (w/ Mos Def Acapella)",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_i’ll-be-there-mos-def_1.mp3",
    links: {},
  },
  {
    title: "Be Right There",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_i’ll-be-there_1.mp3",
    links: {},
  },
  {
    title: "Leave It All to Me (from iCarly)",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["experimental", "pop"],
    work: ["production", "arranging"],
    credits: [],
    genreLabel: "experimental / pop",
    workLabel: "production · arranging · guitar",
    src: "audio/jsj_leave-it-all-to-me_1.mp3",
    links: {},
  },
  {
    title: "Moonroof",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_moonroof_1.mp3",
    links: {},
  },
  {
    title: "Murder",
    artist: "Jack St Jean",
    date: "202303",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_murder-v2_1.mp3",
    links: {},
  },
  {
    title: "My World",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["hiphop", "boom bap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / boom bap",
    workLabel: "production",
    src: "audio/jsj_my-world_1.mp3",
    links: {},
  },
  {
    title: "Nerevar",
    artist: "Jack St Jean",
    date: "202302",
    genres: ["hiphop"],
    work: ["production", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_nerevar_1.mp3",
    links: {},
  },
  {
    title: "Nineteen",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["indie", "pop", "dance"],
    work: ["production", "composition", "guitar"],
    credits: [],
    genreLabel: "indie / pop / dance",
    workLabel: "production · composition · guitar",
    src: "audio/jsj_nineteen_1.mp3",
    links: {},
  },
  {
    title: "Nocturne",
    artist: "Jack St Jean",
    date: "202208",
    genres: ["dance", "stupid"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / stupid",
    workLabel: "production",
    src: "audio/jsj_nocturne_1.mp3",
    links: {},
  },
  {
    title: "Please Clap",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["dance", "dariacore"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / dariacore",
    workLabel: "production",
    src: "audio/jsj_please-clap_1.mp3",
    links: {},
  },
  {
    title: "Pray for Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["experimental"],
    work: ["production"],
    credits: [],
    genreLabel: "experimental",
    workLabel: "production",
    src: "audio/jsj_pray-for-me_1.mp3",
    links: {},
  },
  {
    title: "Segovia",
    artist: "Jack St Jean",
    date: "202210",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_segovia_1.mp3",
    links: {},
  },
  {
    title: "Skipping Rocks",
    artist: "Jack St Jean",
    date: "202309",
    genres: ["hiphop", "dilla time"],
    work: ["production", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_skipping-rocks_1.mp3",
    links: {},
  },
  {
    title: "Stick It",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_stick-it_1.mp3",
    links: {},
  },
  {
    title: "Summertime (by Gershwin)",
    artist: "Jack St Jean",
    date: "202304",
    genres: ["hiphop", "dilla time"],
    work: ["production", "arranging", "guitar", "bass"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_summertime_1.mp3",
    links: {},
  },
  {
    title: "Take Off (w/ Kendrick Lamar Acapella)",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "trap"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / trap",
    workLabel: "production",
    src: "audio/jsj_take-off_1.mp3",
    links: {},
  },
  {
    title: "The Ox",
    artist: "Jack St Jean",
    date: "202111",
    genres: ["hiphop", "rock"],
    work: ["production", "guitar"],
    credits: [],
    genreLabel: "hiphop / rock",
    workLabel: "production · guitar",
    src: "audio/jsj_the-ox_1.mp3",
    links: {},
  },
  {
    title: "This Beat Ended Hip Hop for Good",
    artist: "Jack St Jean",
    date: "202103",
    genres: ["hiphop", "stupid"],
    work: ["composition", "guitar"],
    credits: [],
    genreLabel: "hiphop / stupid",
    workLabel: "composition · guitar",
    src: "audio/jsj_this-beat-ended-hip-hop-for-good_1.mp3",
    links: {},
  },
  {
    title: "Trying League of Legends",
    artist: "Jack St Jean",
    date: "202212",
    genres: ["dance", "dariacore"],
    work: ["production"],
    credits: [],
    genreLabel: "dance / dariacore",
    workLabel: "production",
    src: "audio/jsj_trying-league-of-legends_1.mp3",
    links: {},
  },
  {
    title: "You and Me",
    artist: "Jack St Jean",
    date: "202206",
    genres: ["hiphop", "dilla time"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / dilla time",
    workLabel: "production",
    src: "audio/jsj_u&e_1.mp3",
    links: {},
  },
  {
    title: "U&I v1",
    artist: "Jack St Jean",
    date: "202304",
    genres: ["hiphop", "lofi"],
    work: ["production", "composition", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / hiphop",
    workLabel: "production · composition · guitar · bass",
    src: "audio/jsj_u&i-v1_1.mp3",
    links: {},
  },
  {
    title: "U&I v2",
    artist: "Jack St Jean",
    date: "202305",
    genres: ["experimental", "lofi"],
    work: ["production", "composition", "guitar", "bass"],
    credits: [],
    genreLabel: "lofi / experimental",
    workLabel: "production · composition · guitar · bass",
    src: "audio/jsj_u&i-v2_1.mp3",
    links: {},
  },
  {
    title: "Up Early",
    artist: "Jack St Jean",
    date: "202207",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/jsj_up-early_1.mp3",
    links: {},
  },
  {
    title: "Westcoast",
    artist: "Jack St Jean",
    date: "202203",
    genres: ["hiphop", "g-funk"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop / g-funk",
    workLabel: "production",
    src: "audio/jsj_westcoast_1.mp3",
    links: {},
  },

  // ─── Cielago's Bootlegs ────────────────────────────────────────────────────
  {
    title: "All My Friends Are Stoners",
    artist: "Cielago's Bootlegs",
    date: "202406",
    genres: ["indie", "rock"],
    work: ["mixing", "production"],
    credits: [],
    genreLabel: "indie / rock",
    workLabel: "mixing · production",
    src: "audio/cielagos-bootlegs_all-my-friends-are-stoners.wav",
    links: {spotify: "https://open.spotify.com/track/4Ryqj2jlT9l8dnm98AxeTE?si=75888c15b96e4e43"},
  },

  // ─── Wizedev ───────────────────────────────────────────────────────────────
  {
    title: "Intro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production", "guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · guitar · composition",
    src: "audio/wizedev_intro.mp3",
    links: {
      spotify: "https://open.spotify.com/track/1RlXOUfT83bYYEo1jiiFa3?si=d031019e9e924fdf",
      youtube: "https://youtu.be/A52amUPtuIU?si=gjnWf5O4FDtfQAep",
      applemusic: "https://music.apple.com/us/song/intro/1708496187",
    },
  },
  {
    title: "Rewind",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition",
    src: "audio/wizedev_rewind.mp3",
    links: {
      spotify: "https://open.spotify.com/track/6922K7B9YVskfVhDvj5lu7?si=6a74d6379be64d3e",
      youtube: "https://youtu.be/YNtUuYsL9MM?si=pJ2e7H45O6fb9Xa_",
      applemusic: "https://music.apple.com/us/song/rewind/1708496188",
    },
  },
  {
    title: "I'll Be There",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production", "bass"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition · bass",
    src: "audio/wizedev_i'll-be-there.mp3",
    links: {
      spotify: "https://open.spotify.com/track/1jnvlqiWMKxxk5RbGBnTbl?si=6903301db462462f",
      youtube: "https://youtu.be/iEOFeoOW7Pw?si=4v_MicvA2Zue92kK",
      applemusic: "https://music.apple.com/us/song/ill-be-there/1708496190",
    },
  },
  {
    title: "Long Night",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition",
    src: "audio/wizedev_long-night.mp3",
    links: {
      spotify: "https://open.spotify.com/track/3mMCNu696bbkubL66hXRIO?si=2971d8bae883433b",
      youtube: "https://youtu.be/bR6lAmxeqoE?si=zkFTYJEnR_Dul7VS",
      applemusic: "https://music.apple.com/us/song/long-night/1708496193",
    },
  },
  {
    title: "Take My Hand",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition",
    src: "audio/wizedev_take-my-hand.mp3",
    links: {
      spotify: "https://open.spotify.com/track/1c28OpvfzQIUy8cUG8PWy2?si=51f08171642c4e09",
      youtube: "https://youtu.be/kWUfpJcwpZY?si=pPuJcjjUVxSWo605",
      applemusic: "https://music.apple.com/us/song/take-my-hand/1708496194",
    },
  },
  {
    title: "Zion",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production · composition",
    src: "audio/wizedev_zion.mp3",
    links: {
      spotify: "https://open.spotify.com/track/6yA1K91dfNn1Do7cT7qBPx?si=4c2c922192944f8a",
      youtube: "https://youtu.be/b79_yHEQ1s8?si=JZGlFVb3j5sNQKq8",
      applemusic: "https://music.apple.com/us/song/zion/1708496195",
    },
  },
  {
    title: "Outro",
    artist: "Wizedev",
    date: "202310",
    genres: ["hiphop"],
    work: ["production"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "production",
    src: "audio/wizedev_outro.mp3",
    links: {
      spotify: "https://open.spotify.com/track/1rMFKbPoGiAwkBHdM60uuU?si=b067955a9b1341b6",
      youtube: "https://youtu.be/wtftYpdiaH4?si=wN1nBSp8TMEUa4W-",
      applemusic: "https://music.apple.com/us/song/outro/1708496198",
    },
  },

  // ─── Porcelain Parrot ──────────────────────────────────────────────────────
  {
    title: "Dreams",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_dreams.wav",
    links: {
      spotify: "https://open.spotify.com/track/6z3GTHCgG8xxfJMYUcIKut?si=d998ee7658f64ba6",
      youtube: "https://youtu.be/nq8HZqhlUUs?si=4i8LSrkYcXmZvzIu",
      applemusic: "https://music.apple.com/us/song/dreams/6772474075",
      bandcamp: "https://porcelainparrot.bandcamp.com/track/dreams-2",
    },
  },
  {
    title: "Volume Negates Luck",
    artist: "Porcelain Parrot",
    date: "202605",
    genres: ["punk", "shoegaze"],
    work: ["recording"],
    credits: [],
    genreLabel: "punk / shoegaze",
    workLabel: "recording",
    src: "audio/porcelain-parrot_volume-negates-luck.wav",
    links: {
      spotify: "https://open.spotify.com/track/7lFIopvdTFxR75r9TMSl1z?si=fecfce5444db4bb1",
      youtube: "https://youtu.be/X3MA7o4OU1o?si=ePtVdX816bZLZsbI",
      applemusic: "https://music.apple.com/us/song/volume-negates-luck/6772474074",
      bandcamp: "https://porcelainparrot.bandcamp.com/track/volume-negates-luck-2",
    },
  },

  // ─── Lemongrass Roots Band ─────────────────────────────────────────────────
  {
    title: "Bowling Green",
    artist: "C.H. Warren",
    date: "202606",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/ch-warren_bowling-green.wav",
    links: {},
  },
  {
    title: "I Don't Want Your Millions",
    artist: "C.H. Warren",
    date: "202606",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/ch-warren_millions.wav",
    links: {},
  },
  {
    title: "Blue Moon of Kentucky",
    artist: "C.H. Warren",
    date: "202606",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/ch-warren_blue-moon-kentucky.wav",
    links: {},
  },
  {
    title: "Diamond Joe",
    artist: "C.H. Warren",
    date: "202606",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/ch-warren_diamond-joe.wav",
    links: {},
  },

  // ─── Lemongrass Roots Band ─────────────────────────────────────────────────
  {
    title: "Whiskey Before Breakfast",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_whiskey-before-breakfast.wav",
    links: {},
  },
  {
    title: "Tswv Yexus Lub Npe",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_tswv-yexus-lub-npe.wav",
    links: {},
  },
  {
    title: "Old Home Place",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_old-home-place.wav",
    links: {},
  },
  {
    title: "Kuv Tus Kwvluag",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_kuv-tus-kwvluag.wav",
    links: {},
  },
  {
    title: "East Tennessee Blues",
    artist: "Lemongrass Roots Band",
    date: "202203",
    genres: ["bluegrass"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "bluegrass",
    workLabel: "recording · mixing · mastering",
    src: "audio/lemongrass_east-tennessee-blues.wav",
    links: {},
  },

  // ─── kinfolk ───────────────────────────────────────────────────────────────
  {
    title: "She's Not Like Me",
    artist: "kinfolk",
    date: "202504",
    genres: ["indie", "folk"],
    work: ["production", "recording", "mixing", "mastering", "arranging", "guitar", "bass"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "production · composition · arranging · recording · mixing · mastering · guitar · bass",
    src: "audio/kinfolk_shes-not-like-me.wav",
    links: {
      spotify: "https://open.spotify.com/track/1QZFFJanGAo4ZkDwndgTxu?si=7b18ec4f27ff4cb0",
      applemusic: "https://music.apple.com/us/song/shes-not-like-me/1805673981",
      youtube: "https://youtu.be/UJnhk_iKwyA?si=WOhJLA-jy2B-5Jv2",
      soundcloud: "",
    },
  },

  // ─── Kai Moscow ────────────────────────────────────────────────────────────
  {
    title: "Pinball Number Count (from Sesame Street)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_pinball-number-count.wav",
    links: {},
  },
  {
    title: "Le Bleury (by Anomalie)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "fusion", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_le-bleury.wav",
    links: {},
  },
  {
    title: "Lean On Me (by Bill Withers)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["soul", "live"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "soul",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_lean-on-me.wav",
    links: {},
  },
  {
    title: "Strasbourg St Denis (by Roy Hargrove)",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["jazz", "funk"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / funk",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_strasbourg-st-denis.wav",
    links: {},
  },
  {
    title: "Songs for Bilbao",
    artist: "Kai Moscow",
    date: "202404",
    genres: ["latin", "jazz", "fusion"],
    work: ["recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "latin / jazz / fusion",
    workLabel: "recording · mixing · mastering",
    src: "audio/kai-moscow_songs-for-bilbao.wav",
    links: {},
  },

  // ─── Industrial Coffee Pot ─────────────────────────────────────────────────
  {
    title: "Just Shwangen - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_just-shwangen.wav",
    links: {
      spotify: "https://open.spotify.com/track/7iqhE5CBAbGfrIPWKNf32Y?si=42a539e449cd4531",
      applemusic: "https://music.apple.com/us/song/just-shwangen-live/1876635251",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/just-swangin-1?in=industrial-coffee-pot/sets/it-will-be-different-live&si=2d418fc8f2c34dda91b6d7446fd6cd79&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/just-swangen-3",
      youtube: "https://youtu.be/s4U8MnzRmoU?si=f_ez4NigoW-SWAJc",
    },
  },
  {
    title: "To the Moon River - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_to-the-moon-river.wav",
    links: {
      spotify: "https://open.spotify.com/track/5KlAQJq67d7C6aDiB4XRPT?si=ba9412b069314825",
      applemusic: "https://music.apple.com/us/song/to-the-moon-river-live/1876635253",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/to-the-moon-river-2?in=industrial-coffee-pot/sets/it-will-be-different-live&si=26ce0dcf48e14eb384f2fafc6ffe0022&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/fly-me-to-moon-river",
      youtube: "",
    },
  },
  {
    title: "San Francisco Pilot - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_san-francisco-pilot.wav",
    links: {
      spotify: "https://open.spotify.com/track/7I5xCH2b0Z0oTyEuwZJjKc?si=89c72685b51e4885",
      applemusic: "https://music.apple.com/us/song/san-francisco-pilot-live/1876635254",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/san-francisco-pilot-3?in=industrial-coffee-pot/sets/it-will-be-different-live&si=1a418a94f07745828416421bd48a3bd4&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/san-francisco-pilot",
      youtube: "https://youtu.be/owkxmWBTCZs?si=qdZbbiltcii6cwn_",
    },
  },
  {
    title: "Softly - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_softly.wav",
    links: {spotify: "https://open.spotify.com/track/3CmtqDZ8dkYb3qeHsGtaDV?si=d98b64c836dc403d",
      applemusic: "https://music.apple.com/us/song/softly-live/1876635255",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/softly-4?in=industrial-coffee-pot/sets/it-will-be-different-live&si=09f59ba30d444590990835585ef0b204&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/softly-2",
      youtube: "https://youtu.be/26x2Pgbx9o8?si=jRdc2J9ofBtvaJjY",
    },
  },
  {
    title: "Rain and Snow - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / bossa",
    workLabel: "mixing · mastering",
    src: "audio/icp_rain-and-snow.wav",
    links: {spotify: "https://open.spotify.com/track/6S1Eg2fpwGOBV2rAZ92E7B?si=e3143ea683884be9",
      applemusic: "https://music.apple.com/us/song/rain-and-snow-live/1876635256",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/rain-and-snow-5?in=industrial-coffee-pot/sets/it-will-be-different-live&si=8a289b7f404e4c9eac50d46f1e0d702e&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/rain-and-snow-3",
      youtube: "",
    },
  },
  {
    title: "Our Love - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_our-love.wav",
    links: {spotify: "https://open.spotify.com/track/3cf567vq1NfTryccpwjwIz?si=661bdaa1bdb64dd3",
      applemusic: "https://music.apple.com/us/song/our-love-live/1876635257",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/our-love-6?in=industrial-coffee-pot/sets/it-will-be-different-live&si=2d35df1cd0cb4db589430115cd6bd248&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/our-love",
      youtube: "https://youtu.be/iUQ6LzhQQP0?si=wFVs4vMrkIF8R4yo",
    },
  },
  {
    title: "Another Case of the No Good Reason - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "fusion", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "mixing · mastering",
    src: "audio/icp_another-case.wav",
    links: {
      spotify: "https://open.spotify.com/track/1rJHtGLCogO1xRSzy2cPnr?si=1fe987e550014907",
      applemusic: "https://music.apple.com/us/song/another-case-of-the-no-good-reason-live/1876635258",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/another-case-7?in=industrial-coffee-pot/sets/it-will-be-different-live&si=a336797841d247e7bd4adb2200a8d93f&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/another-case-3",
      youtube: "https://youtu.be/0UADv1OVI6o?si=kFIfeKBB2uCaftz5",
    },
  },
  {
    title: "Just Friends - Live",
    artist: "Industrial Coffee Pot",
    date: "202602",
    genres: ["jazz", "live"],
    work: ["mixing", "mastering"],
    credits: [],
    genreLabel: "jazz",
    workLabel: "mixing · mastering",
    src: "audio/icp_just-friends.wav",
    links: {
      spotify: "https://open.spotify.com/track/4up6G9t6Vpu2lnDHOBMLAx?si=d0676886814f43b9",
      applemusic: "https://music.apple.com/us/song/just-friends-live/1876635260",
      soundcloud: "https://soundcloud.com/industrial-coffee-pot/just-friends-8?in=industrial-coffee-pot/sets/it-will-be-different-live&si=ed841c549e884c8b996adfa3db65f88b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      bandcamp: "https://industrialcoffeepot.bandcamp.com/track/just-friends",
      youtube: "https://youtu.be/qwV1UuJlzPg?si=XZyMlg5EGR-PL330",
    },
  },

  // ─── Floral Dilemma ────────────────────────────────────────────────────────
  {
    title: "Edging on Merrimon",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing",
    src: "audio/floral-dilemma_edging-on-merrimon.wav",
    links: {},
  },
  {
    title: "Misty Rain",
    artist: "Floral Dilemma",
    date: "202312",
    genres: ["jazz", "fusion"],
    work: ["recording", "mixing"],
    credits: [],
    genreLabel: "jazz / fusion",
    workLabel: "recording · mixing",
    src: "audio/floral-dilemma_misty-rain.wav",
    links: {},
  },

  // ─── Donnie Black ──────────────────────────────────────────────────────────
  {
    title: "Summer's Over (Introlude)",
    artist: "Donnie Black",
    date: "202509",
    genres: ["r&b"],
    work: ["production", "recording", "mixing", "mastering"],
    credits: [],
    genreLabel: "r&b",
    workLabel: "production · recording · mixing · mastering",
    src: "audio/donnie-black_summers-over.wav",
    links: {
      spotify: "https://open.spotify.com/track/2n6egAJsgNfknXPpkY9R0I?si=66c89158f41241fc",
      applemusic: "https://music.apple.com/us/song/summers-over-introlude/1838278762",
    },
  },
  // {
  //   title: "Be Free",
  //   artist: "Donnie Black",
  //   date: "",
  //   genres: [],
  //   work: [],
  //   credits: [],
  //   genreLabel: "",
  //   workLabel: "",
  //   src: "audio/donnie-black_be-free.wav",
  //   links: {},
  // },

  // ─── Terrordome ────────────────────────────────────────────────────────────
  {
    title: "Outro",
    artist: "Terrordome",
    date: "202605",
    genres: ["hiphop"],
    work: ["guitar"],
    credits: [],
    genreLabel: "hiphop",
    workLabel: "guitar",
    src: "audio/terrordome_outro.mp3",
    links: {
      spotify: "https://open.spotify.com/track/56BPM3jOPx66rQFFjEnCfh?si=80cc56dbed8f4cfc",
      applemusic: "https://music.apple.com/us/song/outro/1689486215",
      youtube: "https://youtu.be/9IPXXyTvqW4?si=DYQOw2EDwOfY7l5Q",
    },
  },

  // ─── Pulse ──────────────────────────────────────────────────────────────────
  {
    title: "All My Life",
    artist: "Pulse",
    date: "202501",
    genres: ["indie", "rock", "britpop"],
    work: ["recording"],
    credits: [],
    genreLabel: "indie / rock / britpop",
    workLabel: "guitar",
    src: "audio/pulse_all-my-life.mp3",
    links: {
      spotify: "https://open.spotify.com/track/1FgCveTVoiacqvDIesGOfe?si=fc25d0120d69435c",
      applemusic: "https://music.apple.com/us/song/all-my-life/1789975736",
      youtube: "https://youtu.be/IS6RBQNeaXw?si=xEh3qBKkFrCnIHWa",
    },
  },

  // ─── Frances Eliza ─────────────────────────────────────────────────────────
  {
    title: "the words i didn't say",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "pop", "rock"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / pop / rock",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_words-i-didn't-say.wav",
    links: {
      spotify: "https://open.spotify.com/track/2pamQ6TKeHWtizdni6C5aG?si=48fc8d23c96443b8",
      soundcloud: "https://soundcloud.com/frances-eliza/drove-me-away?si=f2e7eeb9ff5147e7822c9e0e6df48e31&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      applemusic: "https://music.apple.com/us/song/the-words-i-didnt-say/6763442175",
      bandcamp: "https://franceseliza.bandcamp.com/track/the-words-i-didnt-say",
    },
  },
  {
    title: "drove me away",
    artist: "Frances Eliza",
    date: "202605",
    genres: ["indie", "folk"],
    work: ["mixing", "recording"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_drove-me-away.wav",
    links: {
      spotify: "https://open.spotify.com/track/4zvgpO7oSC278tMaCMkQtI?si=111b48df3f19430f",
      soundcloud: "https://soundcloud.com/frances-eliza/drove-me-away?si=97b22c441d5b40cc82349fef2698ba8f&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      applemusic: "https://music.apple.com/us/song/drove-me-away/6763442176",
      bandcamp: "https://franceseliza.bandcamp.com/track/drove-me-away",
    },
  },
  {
    title: "Notice Me",
    artist: "Frances Eliza",
    date: "202305",
    genres: ["indie", "rock"],
    work: ["production", "recording", "mixing", "guitar"],
    credits: [],
    genreLabel: "indie / rock",
    workLabel: "production · recording · mixing · guitar",
    src: "audio/frances-eliza_notice-me.wav",
    links: {
      spotify: "https://open.spotify.com/track/5iFVb2mQvnklH1z21LuTkS?si=171852387fee4c9f",
      soundcloud: "https://soundcloud.com/frances-eliza/frances-eliza-notice-me?si=9ed0912032824dd2b545506786d8e17d&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      applemusic: "https://music.apple.com/us/song/notice-me/1688648915",
      bandcamp: "https://franceseliza.bandcamp.com/track/notice-me",
    },
  },
  {
    title: "Nowhere",
    artist: "Frances Eliza",
    date: "202501",
    genres: ["indie", "folk"],
    work: ["recording", "mixing"],
    credits: [],
    genreLabel: "indie / folk",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_nowhere.wav",
    links: {
      spotify: "https://open.spotify.com/track/7oeRr9YqqUw9Bl5wf0M2jq?si=843979deef604c0a",
      youtube: "https://youtu.be/G4x0ughN5ck?si=3Ds4bgQN-snpChMp",
      soundcloud: "https://soundcloud.com/frances-eliza/nowhere?si=20dfdc0fe394446085aea9d23ffd785b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      applemusic: "https://music.apple.com/us/song/nowhere/1788877799",
      bandcamp: "https://franceseliza.bandcamp.com/track/nowhere",
    },
  },
  {
    title: "Kind of Love",
    artist: "Frances Eliza",
    date: "202510",
    genres: ["indie", "rock"],
    work: ["recording", "mixing"],
    credits: [],
    genreLabel: "indie / rock",
    workLabel: "mixing · recording (vocals)",
    src: "audio/frances-eliza_kind-of-love.wav",
    links: {
      spotify: "https://open.spotify.com/track/6vkwFyronel0b6R4PZTg3d?si=61f78b88dd2a44e9",
      soundcloud: "https://soundcloud.com/frances-eliza/mastered-16-44-1-kind-of-love?si=f2df17fc798f44a19d43dc3fd7b04d60&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing",
      applemusic: "https://music.apple.com/us/song/kind-of-love/1837786405",
      bandcamp: "https://franceseliza.bandcamp.com/track/kind-of-love",
    },
  }
];
// ───────────────────────────────────────────────────────────────────────────
